In [1]:
from InfoExtractorChileURL_class import InfoExtractorChileURL

from datetime import datetime, timedelta
#import InfoExtractor_class as iex
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [2]:
asd = InfoExtractorChileURL()

In [3]:
from_date = datetime(2000, 1, 1)
to_date = datetime(2023, 7, 2)

In [4]:
prueba = asd.extractInfo(from_date, to_date)

In [5]:
from InfoFormatterChile_class import InfoFormatterChile

In [6]:
afd = InfoFormatterChile()

In [7]:
type(prueba)

pandas.core.frame.DataFrame

In [8]:
prueba

,1,2,3,4,5
0,None,None,None,None,None
1,None,None,None,None,None
2,2000-01-02 16:36:2522 km al S de Petorca,2000-01-02 19:36:25,-32.446 -70.923,95 km,2.7 Mc
3,2000-01-02 15:55:5518 km al NO de Illapel,2000-01-02 18:55:55,-31.535 -71.318,36 km,3.8 Mc
4,2000-01-02 02:03:1316 km al SO de Melipilla,2000-01-02 05:03:13,-33.787 -71.339,46 km,3.7 Mc
...,...,...,...,...,...
138077,2023-07-01 23:04:0710 km al NO de Andacollo,2023-07-02 03:04:07,-30.147 -71.124,75 km,3.0 Ml
138078,2023-07-01 22:57:4826 km al SO de Ollagüe,2023-07-02 02:57:48,-21.411 -68.406,122 km,2.7 Ml
138079,2023-07-01 22:57:43120 km al O de Valparaíso,2023-07-02 02:57:43,-33.098 -72.905,39 km,3.6 Ml
138080,2023-07-01 22:03:0233 km al SE de Vichuquén,2023-07-02 02:03:02,-35.082 -71.727,55 km,2.8 Ml
138081,2023-07-01 21:12:1754 km al S de Mina Collahuasi,2023-07-02 01:12:17,-21.285 -68.829,116 km,2.9 Ml

In [10]:
prueba2 = afd.formatInfoChile(prueba)

In [12]:
prueba2

,Fecha local,Fecha UTC,Latitud,Longitud,Profundidad(Km),Magnitud,TipoDeMagnitud,Referencia
0,2000-01-02 16:36:25,2000-01-02 19:36:25,-32.446,-70.923,95.0,2.7,Mc,22 km al S de Petorca
1,2000-01-02 15:55:55,2000-01-02 18:55:55,-31.535,-71.318,36.0,3.8,Mc,18 km al NO de Illapel
2,2000-01-02 02:03:13,2000-01-02 05:03:13,-33.787,-71.339,46.0,3.7,Mc,16 km al SO de Melipilla
3,2000-01-02 00:42:12,2000-01-02 03:42:12,-33.410,-70.880,82.0,2.5,Mc,22 km al O de Santiago
4,2000-01-03 10:35:31,2000-01-03 13:35:31,-32.747,-71.685,15.0,3.5,Mc,34 km al N de Valparaíso
...,...,...,...,...,...,...,...,...
129493,2023-07-01 23:04:07,2023-07-02 03:04:07,-30.147,-71.124,75.0,3.0,Ml,10 km al NO de Andacollo
129494,2023-07-01 22:57:48,2023-07-02 02:57:48,-21.411,-68.406,122.0,2.7,Ml,26 km al SO de Ollagüe
129495,2023-07-01 22:57:43,2023-07-02 02:57:43,-33.098,-72.905,39.0,3.6,Ml,120 km al O de Valparaíso
129496,2023-07-01 22:03:02,2023-07-02 02:03:02,-35.082,-71.727,55.0,2.8,Ml,33 km al SE de Vichuquén
129497,2023-07-01 21:12:17,2023-07-02 01:12:17,-21.285,-68.829,116.0,2.9,Ml,54 km al S de Mina Collahuasi